# -- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS AS C
WHERE 'Milk' IN (SELECT NAME FROM CART_PRODUCTS WHERE CART_ID = C.CART_ID)
AND 'Yogurt' IN (SELECT NAME FROM CART_PRODUCTS WHERE CART_ID = C.CART_ID)
GROUP BY CART_ID
ORDER BY CART_ID