-- 코드를 입력하세요
SELECT LEFT(SALES_DATE, 10) AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    UNION ALL 
    SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE  FROM OFFLINE_SALE
) AS A
WHERE LEFT(SALES_DATE, 7) = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID