-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES) * PRICE AS TOTAL_SALES
    FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS S
    WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID AND LEFT(SALES_DATE, 7) = '2022-01'
    GROUP BY B.AUTHOR_ID, CATEGORY, B.BOOK_ID
) AS TEMP
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;