-- 코드를 입력하세요

# 자동차 종류가 '트럭' 인 자동차의 대여 기록에 대해서 대여 기간
# SELECT HISTORY_ID, ROUND((
#     CASE 
#     WHEN END_DATE - START_DATE + 1 >= 90 THEN DAILY_FEE * (
#         SELECT (100 - DISCOUNT_RATE) / 100
#         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#         WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'
#     ) * (END_DATE - START_DATE + 1)
#     WHEN END_DATE - START_DATE + 1 >= 30 THEN DAILY_FEE * (
#         SELECT (100 - DISCOUNT_RATE) / 100
#         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#         WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'
#     ) * (END_DATE - START_DATE + 1)
#     WHEN END_DATE - START_DATE + 1 >= 7 THEN DAILY_FEE * (
#         SELECT (100 - DISCOUNT_RATE) / 100
#         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#         WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'
#     ) * (END_DATE - START_DATE + 1)
#     ELSE DAILY_FEE * (END_DATE - START_DATE + 1)
#     END
# ), 0) AS FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H, CAR_RENTAL_COMPANY_CAR AS C
# WHERE H.CAR_ID = C.CAR_ID AND CAR_TYPE = '트럭'
# ORDER BY FEE DESC, HISTORY_ID DESC;

SELECT HISTORY_ID, FLOOR((100 - (
    CASE 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'
    )
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'
    )
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'
    )
    ELSE 0
    END
)) * 0.01 * (DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H, CAR_RENTAL_COMPANY_CAR AS C
WHERE H.CAR_ID = C.CAR_ID AND CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;