-- 코드를 입력하세요
-- SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
-- FROM FOOD_PRODUCT, FOOD_ORDER
-- WHERE FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID AND LEFT(PRODUCE_DATE, 7) = '2022-05'
-- GROUP BY FOOD_PRODUCT.PRODUCT_ID
-- ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_CD;

-- 해답: https://school.programmers.co.kr/questions/47246
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    (P.PRICE * SUM(O.AMOUNT)) TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC