-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE A.PT_NO = P.PT_NO AND A.MDDR_ID = D.DR_ID AND A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' AND LEFT(A.APNT_YMD, 10) = '2022-04-13'
ORDER BY A.APNT_YMD
