SELECT SUM(SCORE) AS SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_DEPARTMENT, HR_EMPLOYEES, HR_GRADE
WHERE HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
    AND HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
    AND YEAR = 2022
GROUP BY HR_EMPLOYEES.EMP_NO
ORDER BY SCORE DESC
LIMIT 1