SELECT
    HR_DEPARTMENT.DEPT_ID, 
    DEPT_NAME_EN, 
    ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT, HR_EMPLOYEES
WHERE HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
GROUP BY HR_DEPARTMENT.DEPT_ID
ORDER BY AVG_SAL DESC